// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package vsphereclient

import (
	"fmt"
	"strings"
)

const (
	// CloneTypeFull is a CloneType of type full.
	CloneTypeFull CloneType = "full"
	// CloneTypeLinked is a CloneType of type linked.
	CloneTypeLinked CloneType = "linked"
	// CloneTypeInstant is a CloneType of type instant.
	CloneTypeInstant CloneType = "instant"
)

var ErrInvalidCloneType = fmt.Errorf("not a valid CloneType, try [%s]", strings.Join(_CloneTypeNames, ", "))

var _CloneTypeNames = []string{
	string(CloneTypeFull),
	string(CloneTypeLinked),
	string(CloneTypeInstant),
}

// CloneTypeNames returns a list of possible string values of CloneType.
func CloneTypeNames() []string {
	tmp := make([]string, len(_CloneTypeNames))
	copy(tmp, _CloneTypeNames)
	return tmp
}

// CloneTypeValues returns a list of the values for CloneType
func CloneTypeValues() []CloneType {
	return []CloneType{
		CloneTypeFull,
		CloneTypeLinked,
		CloneTypeInstant,
	}
}

// String implements the Stringer interface.
func (x CloneType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CloneType) IsValid() bool {
	_, err := ParseCloneType(string(x))
	return err == nil
}

var _CloneTypeValue = map[string]CloneType{
	"full":    CloneTypeFull,
	"linked":  CloneTypeLinked,
	"instant": CloneTypeInstant,
}

// ParseCloneType attempts to convert a string to a CloneType.
func ParseCloneType(name string) (CloneType, error) {
	if x, ok := _CloneTypeValue[name]; ok {
		return x, nil
	}
	return CloneType(""), fmt.Errorf("%s is %w", name, ErrInvalidCloneType)
}

// MarshalText implements the text marshaller method.
func (x CloneType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *CloneType) UnmarshalText(text []byte) error {
	tmp, err := ParseCloneType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *CloneType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
